In [50]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from collections import Counter
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

torch.manual_seed(1337)

eval_iters = 200
n_embd = 384
n_head = 6
n_layer = 6
dropout = 0.2
batch_size = 64 # how many independent sequences will we process in parallel?
block_size = 50 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 500
learning_rate = 3e-4

win_size = 1

In [51]:
def _chunk(x, w):
    '''convert x into overlapping chunks. Chunk size = 2w, overlap size = w'''
    x = x.view(x.size(0), x.size(1)// (w * 2), w * 2, x.size(2))
    chunk_size = list(x.size())
    chunk_size[1] = chunk_size[1] * 2 - 1
    chunk_stride = list(x.stride())
    chunk_stride[1] = chunk_stride[1] // 2

    return x.as_strided(size=chunk_size, stride=chunk_stride)

def _skew(x, dir, pad):
    '''Convert diagonals into columns'''
    x_pad = F.pad(x, dir, value=pad)
    x_pad = x_pad.view(*x_pad.size()[:-2], x_pad.size(-1), x_pad.size(-2))
    return x_pad

def _skewv(x, pad):
    B, C, M, L = x.size()
    x = F.pad(x, (0, M+1), value=pad)
    x = x.view(B, C, -1)
    x = x[:, :, :-M]
    x = x.view(B, C, M, M+L)
    x= x[:,:,:,:-1]
    return x


def sliding_chunk_matmul(q, k, w, pad):
    B,T,C = q.shape

    assert T % (w * 2) == 0
    assert q.shape == k.shape

    chunk_count = T // w- 1

    #q = q.transpose(1,2)
    #k = k.transpose(1,2)

    qchunk = _chunk(q, w)
    kchunk = _chunk(k, w)

    chunked_attn = torch.einsum('bcxd, bcyd->bcxy', (qchunk, kchunk))

    diag_chunk_attn = _skew(chunked_attn, dir=(0,0,0,1), pad=pad)

    diag_attn = diag_chunk_attn.new_empty((B,chunk_count + 1, w, w * 2 + 1))
    
    diag_attn[:, :-1, :, w:] = diag_chunk_attn[:, :, :w, :w+1]
    diag_attn[:, -1, :, w:] = diag_chunk_attn[:, -1, w:, :w+1]

    diag_attn[:, 1:, :, :w] = diag_chunk_attn[:, :, -(w+1):-1, w+1:]
    diag_attn[:, 0, 1:w, 1:w] = diag_chunk_attn[:, 0, :w-1, 1-w:]

    diag_attn = diag_attn.view(B, T, 2 * w +1)#.transpose(2, 1)

    return diag_attn

def sliding_chunk_matmul_v(attn, v, w):
    B,T,C = v.shape

    assert T % (w * 2) == 0
    assert attn.size()[:2] == v.size()[:2]
    assert attn.size(2) == 2 * w + 1

    chunk_count = T // w- 1

    #q = q.transpose(1,2)
    #k = k.transpose(1,2)

    chunk_prob = attn.reshape(B, T//w, w, 2*w+1)

    pad_v = F.pad(v, (0,0,w,w), value=-1)

    chunk_v_size = (B, chunk_count+1, 3*w, C)
    chunk_v_stride = pad_v.stride()
    chunk_v_stride = chunk_v_stride[0], w * chunk_v_stride[1], chunk_v_stride[1], chunk_v_stride[2]
    chunk_v = pad_v.as_strided(size=chunk_v_size, stride=chunk_v_stride)

    skew_prob = _skewv(chunk_prob, pad=0)
    context = torch.einsum('bcwd,bcdh->bcwh', (skew_prob, chunk_v))

    return context.view(B, T, C)

In [55]:
v = torch.rand(1,8,1,384)
k = torch.rand(1,8,1,384)
q = torch.rand(1,8,1,384)

v2 = torch.rand(1,8,10)
k2 = torch.rand(1,8,10)
q2 = torch.rand(1,8,10)

#sliding_chunks_matmul_qk(q,v, 2, 0)
attn = sliding_chunk_matmul(q2, k2, 2, 0)
print(attn)
sliding_chunk_matmul_v(attn, v2, 2)

tensor([[[  0.0000,   0.0000, 105.4151, 100.2493, 107.2933],
         [  0.0000,  99.2229,  97.7906, 102.5746, 100.0020],
         [101.7406,  97.8489, 101.5796,  97.9658,  97.0337],
         [ 97.2459,  98.4757,  99.3992,  96.9243,  99.8543],
         [ 99.1744,  94.8666,  94.9401,  98.0238,  95.7316],
         [102.0182, 100.5831, 104.3084, 104.2916,  98.4363],
         [ 96.1710,  95.2321,  96.6076,  89.6219,  99.3536],
         [ 99.9645, 100.7092,  92.0059,   0.0000,   0.0000]]])


tensor([[[224.1960,  57.8433, 116.3233,  ..., 164.6948,  89.4150, 221.3422],
         [299.8505,  79.8600, 203.8765,  ..., 170.0436, 100.7219, 250.9188],
         [366.8719, 168.1338, 250.5589,  ..., 251.5877, 193.1292, 339.5516],
         ...,
         [353.9279, 164.1116, 225.5667,  ..., 256.9429, 181.1413, 320.4364],
         [147.3955,  31.3558,  22.9997,  ..., 126.0580,  55.3621, 162.0428],
         [186.6535,  45.2265,  76.5405,  ..., 150.7142,  66.0895, 181.9383]]])

In [53]:
class attnSlidingWindow(nn.Module):
    '''
        Attention(Q, K, V ) = softmax( QK^T/√d_k)V 
    
    '''
    #Takes number of embedded, head_size, context length
    def __init__(self, embn, hdim, con_l, drop=0.0):

        super(attnSlidingWindow, self).__init__()
        #dim is (d_k) when sqrt'd it is meant to counter small gradients in large sets of queries and keys
        self.k = nn.Linear(embn, hdim, bias=False)
        self.q = nn.Linear(embn, hdim, bias=False)
        self.v = nn.Linear(embn, hdim, bias=False)
        self.d_k = np.sqrt(hdim)

        self.register_buffer('mask', torch.tril(torch.ones(con_l,con_l)))
        #Simple drop out 
        self.drop = nn.Dropout(drop)

    def forward(self, x, ret_att=False):
        #batch X length X dim
        B,T,C = x.shape
        k = self.k(x)
        q = self.q(x)

        n = sliding_chunk_matmul(q, k, win_size, 0) * k.shape[-1]**-0.5
        n = n.masked_fill(self.mask[:T,:n.shape[-1]]==0, float('-inf'))
        #Drop out referenced later in paper but not in original diagram
        att = self.drop(F.softmax(n, dim=-1))

        v = self.v(x)

        out = sliding_chunk_matmul_v(att, v, win_size)
        if ret_att:
            return out, att 
        return out

In [56]:
#Scaled dot product attention testing
#dim should be size of q and k


windowattn = attnSlidingWindow(384, 10, 50, drop=0.2)

v = torch.rand(1,8,384)



print(windowattn(v))

RuntimeError: The expanded size of the tensor (0) must match the existing size (3) at non-singleton dimension 2.  Target sizes: [1, 0, 0].  Tensor sizes: [0, 3]

In [ ]:
class multiHeadedAttention(nn.Module):
    def __init__(self, n_heads, dims, embn, con_l, dropout=0.0):
        super(multiHeadedAttention, self).__init__()
        #d_k=d_v = dims/h

        self.n_heads = n_heads

        self.attn = nn.ModuleList([attnSlidingWindow(embn, dims, con_l) for _ in range(n_heads)])
        #Final linear layer after concat and attention
        self.fc = nn.Linear(n_heads*dims, embn)

        self.drop = nn.Dropout(dropout)
        

    def forward(self, x):
        out = torch.cat([h(x) for h in self.attn], dim=-1)
        out = self.drop(self.fc(out))
        return out

In [ ]:
#heads, d_model, d_km d_v as per the paper
torch.manual_seed(1337)
multiHead = multiHeadedAttention(6, 50, 384, 512, dropout=0.2)

#batches, dims, dimensionalityxn_heads

v = torch.rand(1,40,384)


print(multiHead(v))

tensor([[[-2.1719, -0.0000, -0.2509,  ...,  0.0000, -0.4226,  0.4248],
         [-0.0000,  0.3789, -0.0000,  ..., -0.2896,  0.0174,  0.0112],
         [-0.0468,  0.2999,  0.0749,  ..., -0.3903, -0.1123,  0.0769],
         ...,
         [ 0.0241,  0.2538,  0.0000,  ..., -0.0000, -0.1280,  0.0000],
         [-0.0276,  0.2892, -0.0348,  ..., -0.1963, -0.1106,  0.0966],
         [-0.8195, -0.0000, -0.0624,  ...,  0.2939, -0.2398,  0.1765]]],
       grad_fn=<MulBackward0>)


In [ ]:
class positionFeedFoward(nn.Module):
    def __init__(self, inp, hid, drop=0.0):
        super(positionFeedFoward, self).__init__()
        self.w1 = nn.Linear(inp,4*hid)
        self.w2 = nn.Linear(4*hid,inp)
        self.drop = nn.Dropout(drop)

    def forward(self, x):

        x = self.w2(F.relu(self.w1(x)))
        x = self.drop(x)

        return x

In [ ]:
class Decoder(nn.Module):
    '''Combinds MultiHeadedAttention and FeeForward, three layers'''
    def __init__(self, nheads, embn, con_l, drop=0.0):
        super(Decoder, self).__init__()
        head_size = embn // nheads
        self.slf_attn = multiHeadedAttention(nheads, head_size,embn, con_l, dropout=drop)
        
        self.ffn = positionFeedFoward(embn, embn, drop=drop)

        self.norm1 = nn.LayerNorm(embn)
        self.norm2 = nn.LayerNorm(embn)

    def forward(self, x):
        x = x + self.slf_attn(self.norm1(x))
        x = x + self.ffn(self.norm2(x))

        return x

In [ ]:
#heads, d_model, d_km d_v as per the paper
enc = Decoder(8, 64, 512)
#batches, dims, dimensionalityxn_heads

v = torch.rand(1,512,64)


enc(v)

tensor([[[ 0.2074, -0.2719,  0.1172,  ..., -0.1297, -0.4173,  1.0757],
         [ 0.1308,  0.3874, -0.0639,  ...,  0.1979,  0.6255,  0.5990],
         [ 0.2865,  0.0901,  1.0752,  ...,  0.2882,  0.0063,  1.0283],
         ...,
         [ 1.0970,  0.5482,  0.8202,  ...,  0.5679,  1.2668,  0.0970],
         [ 0.7362,  0.4938,  1.2445,  ...,  0.6451,  0.3430,  0.4242],
         [ 1.2710,  0.4392,  0.3721,  ..., -0.1701,  0.5776,  0.2623]]],
       grad_fn=<AddBackward0>)

In [ ]:
class languageModel(nn.Module):
    '''Decoder model'''
    def __init__(
            self, n_vocab, embn, n_layers, n_head, dropout=0.2 , con_l=200
    ):
        super(languageModel, self).__init__()
        self.con_l = con_l
        self.word_emb = nn.Embedding(n_vocab, embn)
        self.pos_enc = nn.Embedding(con_l, embn)
        self.stack = nn.Sequential(
            *[Decoder( n_head, embn, con_l, drop=dropout) for _ in range(n_layers)]
        )
       
        self.layer_norm = nn.LayerNorm(embn)
        self.fc = nn.Linear(embn, n_vocab)

        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, x, tar=None):
        #batch, time
        B, T = x.shape

        tok = self.word_emb(x)
        pos = self.pos_enc(torch.arange(T, device=device))
        x = tok + pos
        x = self.stack(x)
        x = self.layer_norm(x)
        logits = self.fc(x)

        if tar is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            tar = tar.view(B*T)
            loss = F.cross_entropy(logits, tar)

        return logits, loss
    
    def generate(self, x, max_length):
        #x is a BxT array of in current context
        for _ in range(max_length):
            x_cond = x[:, -self.con_l:]
            logits, loss = self(x_cond)
            logits = logits[:,-1,:]
            probs = F.softmax(logits, dim=-1)
            x_next = torch.multinomial(probs, num_samples=1)
            x = torch.cat((x, x_next), dim=1)

        return x
    

In [ ]:

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

torch.manual_seed(1337)

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]


# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss(model):
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits = model(X)[0]
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = Y.view(B*T)
            loss = F.cross_entropy(logits, targets)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

In [31]:
model = languageModel(vocab_size,  384,6, 6, con_l=50
    )
m = model.to(device)
# print the number of parameters in the model
#print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(next(m.parameters()).is_cuda)
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss(model)
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    #B, T, C = logits.shape
    #logits = logits.view(B*T, C)
    #targets = yb.view(B*T)
    #loss = F.cross_entropy(logits, targets)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_length=500)[0].tolist()))
#open('more.txt', 'w').write(decode(m.generate(context, max_new_tokens=10000)[0].tolist()))

True


RuntimeError: The expanded size of the tensor (0) must match the existing size (64) at non-singleton dimension 1.  Target sizes: [64, 0, 0].  Tensor sizes: [64, 0]